# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.10.0-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.10.0-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/velea/work/easyflags/thirdparty/autojson

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/velea/work/easyflags/thirdparty/autojson

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/cmake-3.10.0-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/cmake-3.10.0-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/cmake-3.10.0-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/cmake-3.10.0-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-3.10.0-Linux-x86_64/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/cmake-3.10.0-Linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/cmake-3.10.0-Linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.10.0-Linux-x86_64/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/velea/work/easyflags/thirdparty/autojson/CMakeFiles /home/velea/work/easyflags/thirdparty/autojson/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/velea/work/easyflags/thirdparty/autojson/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named autojson

# Build rule for target.
autojson: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 autojson
.PHONY : autojson

# fast build rule for target.
autojson/fast:
	$(MAKE) -f CMakeFiles/autojson.dir/build.make CMakeFiles/autojson.dir/build
.PHONY : autojson/fast

#=============================================================================
# Target rules for targets named autojson-bin

# Build rule for target.
autojson-bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 autojson-bin
.PHONY : autojson-bin

# fast build rule for target.
autojson-bin/fast:
	$(MAKE) -f CMakeFiles/autojson-bin.dir/build.make CMakeFiles/autojson-bin.dir/build
.PHONY : autojson-bin/fast

bin/Bin.o: bin/Bin.cpp.o

.PHONY : bin/Bin.o

# target to build an object file
bin/Bin.cpp.o:
	$(MAKE) -f CMakeFiles/autojson-bin.dir/build.make CMakeFiles/autojson-bin.dir/bin/Bin.cpp.o
.PHONY : bin/Bin.cpp.o

bin/Bin.i: bin/Bin.cpp.i

.PHONY : bin/Bin.i

# target to preprocess a source file
bin/Bin.cpp.i:
	$(MAKE) -f CMakeFiles/autojson-bin.dir/build.make CMakeFiles/autojson-bin.dir/bin/Bin.cpp.i
.PHONY : bin/Bin.cpp.i

bin/Bin.s: bin/Bin.cpp.s

.PHONY : bin/Bin.s

# target to generate assembly for a file
bin/Bin.cpp.s:
	$(MAKE) -f CMakeFiles/autojson-bin.dir/build.make CMakeFiles/autojson-bin.dir/bin/Bin.cpp.s
.PHONY : bin/Bin.cpp.s

src/Error.o: src/Error.cpp.o

.PHONY : src/Error.o

# target to build an object file
src/Error.cpp.o:
	$(MAKE) -f CMakeFiles/autojson.dir/build.make CMakeFiles/autojson.dir/src/Error.cpp.o
.PHONY : src/Error.cpp.o

src/Error.i: src/Error.cpp.i

.PHONY : src/Error.i

# target to preprocess a source file
src/Error.cpp.i:
	$(MAKE) -f CMakeFiles/autojson.dir/build.make CMakeFiles/autojson.dir/src/Error.cpp.i
.PHONY : src/Error.cpp.i

src/Error.s: src/Error.cpp.s

.PHONY : src/Error.s

# target to generate assembly for a file
src/Error.cpp.s:
	$(MAKE) -f CMakeFiles/autojson.dir/build.make CMakeFiles/autojson.dir/src/Error.cpp.s
.PHONY : src/Error.cpp.s

src/JSON.o: src/JSON.cpp.o

.PHONY : src/JSON.o

# target to build an object file
src/JSON.cpp.o:
	$(MAKE) -f CMakeFiles/autojson.dir/build.make CMakeFiles/autojson.dir/src/JSON.cpp.o
.PHONY : src/JSON.cpp.o

src/JSON.i: src/JSON.cpp.i

.PHONY : src/JSON.i

# target to preprocess a source file
src/JSON.cpp.i:
	$(MAKE) -f CMakeFiles/autojson.dir/build.make CMakeFiles/autojson.dir/src/JSON.cpp.i
.PHONY : src/JSON.cpp.i

src/JSON.s: src/JSON.cpp.s

.PHONY : src/JSON.s

# target to generate assembly for a file
src/JSON.cpp.s:
	$(MAKE) -f CMakeFiles/autojson.dir/build.make CMakeFiles/autojson.dir/src/JSON.cpp.s
.PHONY : src/JSON.cpp.s

src/Parse.o: src/Parse.cpp.o

.PHONY : src/Parse.o

# target to build an object file
src/Parse.cpp.o:
	$(MAKE) -f CMakeFiles/autojson.dir/build.make CMakeFiles/autojson.dir/src/Parse.cpp.o
.PHONY : src/Parse.cpp.o

src/Parse.i: src/Parse.cpp.i

.PHONY : src/Parse.i

# target to preprocess a source file
src/Parse.cpp.i:
	$(MAKE) -f CMakeFiles/autojson.dir/build.make CMakeFiles/autojson.dir/src/Parse.cpp.i
.PHONY : src/Parse.cpp.i

src/Parse.s: src/Parse.cpp.s

.PHONY : src/Parse.s

# target to generate assembly for a file
src/Parse.cpp.s:
	$(MAKE) -f CMakeFiles/autojson.dir/build.make CMakeFiles/autojson.dir/src/Parse.cpp.s
.PHONY : src/Parse.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... autojson"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... autojson-bin"
	@echo "... rebuild_cache"
	@echo "... bin/Bin.o"
	@echo "... bin/Bin.i"
	@echo "... bin/Bin.s"
	@echo "... src/Error.o"
	@echo "... src/Error.i"
	@echo "... src/Error.s"
	@echo "... src/JSON.o"
	@echo "... src/JSON.i"
	@echo "... src/JSON.s"
	@echo "... src/Parse.o"
	@echo "... src/Parse.i"
	@echo "... src/Parse.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

