#pragma once
#include "graph_plot.h"

/// this file will be auto-generated by another tool which will be released in the near fututre

#include <autojson>
#include <string>

GraphPlot::Node::Node(Json& j) {
    x_pos = j["x"];
    y_pos = j["y"];
}

GraphPlot::Edge::Edge(Json& j) {
    source = (std::string)j["source"];
    target = (std::string)j["target"];
    is_directed = j["isDirected"];
}

GraphPlot::GraphPlot(Json& j) {
    x_size = j["xSize"]; 
    y_size = j["ySize"];
    all_edges = j["edges"];
    node_info = j["nodes"]; 
}


namespace AutoJson {
template<>
AutoJson::Json::Json(const GraphPlot::Edge& rhs) : type(0) {
    (*this)["source"] = rhs.source;
    (*this)["target"] = rhs.target;
    (*this)["isDirected"] = rhs.is_directed;
}

template<>
AutoJson::Json::Json(const GraphPlot::Node& rhs) : type(0) {
    (*this)["x"] = rhs.x_pos;
    (*this)["y"] = rhs.y_pos;
}

template<>
Json::Json(const GraphPlot& rhs) : type(0) {
    (*this)["xSize"] = rhs.x_size;
    (*this)["ySize"] = rhs.y_size;
    (*this)["edges"] = rhs.all_edges;
    (*this)["nodes"] = rhs.node_info;
}
}  // namespace AutoJson


